In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [79]:
data=pd.read_csv("diabetes.csv")

In [80]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [81]:
x=data.drop("Outcome",axis=1).values
y=data["Outcome"].values

In [82]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [83]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4,random_state=45)

##### Scalin

In [84]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

##### KNN algorithm

In [85]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)
y_predict = classifier.predict(x_test)

In [86]:
from sklearn.metrics import confusion_matrix,accuracy_score
cr=confusion_matrix(y_test,y_predict)
ac=accuracy_score(y_test,y_predict)
print(cr)

[[167  36]
 [ 47  58]]


In [87]:
print(ac)


0.7305194805194806


In [88]:
classifier.predict([[2,110,120,40,45,30,0.13,45]])

array([1])

### min max ,robust scaling hw

In [89]:
from sklearn.preprocessing import MinMaxScaler
clas=MinMaxScaler()
x_train1=clas.fit_transform(x_train)
x_test2=clas.transform(x_test)

In [90]:
from sklearn.neighbors import KNeighborsClassifier
classifier1=KNeighborsClassifier(n_neighbors=5)
classifier1.fit(x_train,y_train)
y_predict1 = classifier1.predict(x_test)

In [91]:
from sklearn.metrics import confusion_matrix,accuracy_score
mn=confusion_matrix(y_test,y_predict1)
ss=accuracy_score(y_test,y_predict1)
print(mn)
print(ss)

[[167  36]
 [ 47  58]]
0.7305194805194806


In [92]:
from sklearn.neighbors import KNeighborsClassifier
func=KNeighborsClassifier(n_neighbors=5)
func.fit(x_train,y_train)
y_pred3=func.predict(x_test)

In [93]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_pred3,y_test))
print(confusion_matrix(y_pred3,y_test))

0.7305194805194806
[[167  47]
 [ 36  58]]
