In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
data = pd.read_csv("50_Startups.csv")

In [3]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data["State"].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

In [5]:
#GETTING THE DUMMIES FOR STATE COLUMN
data1 = pd.get_dummies(data["State"])
data1.head()

California  Florida  New York
0       False    False      True
1        True    False     False
2       False     True     False
3       False    False      True
4       False     True     False

In [6]:
#concatinating the data frames
data = pd.concat([data,data1],axis=1)
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit  \
0  165349.20       136897.80        471784.10    New York  192261.83   
1  162597.70       151377.59        443898.53  California  191792.06   
2  153441.51       101145.55        407934.54     Florida  191050.39   
3  144372.41       118671.85        383199.62    New York  182901.99   
4  142107.34        91391.77        366168.42     Florida  166187.94   

   California  Florida  New York  
0       False    False      True  
1        True    False     False  
2       False     True     False  
3       False    False      True  
4       False     True     False

In [7]:
data.drop(["State"],axis=1,inplace=True)

In [8]:
x=data.drop(["Profit"],axis=1)
x

R&D Spend  Administration  Marketing Spend  California  Florida  New York
0   165349.20       136897.80        471784.10       False    False      True
1   162597.70       151377.59        443898.53        True    False     False
2   153441.51       101145.55        407934.54       False     True     False
3   144372.41       118671.85        383199.62       False    False      True
4   142107.34        91391.77        366168.42       False     True     False
5   131876.90        99814.71        362861.36       False    False      True
6   134615.46       147198.87        127716.82        True    False     False
7   130298.13       145530.06        323876.68       False     True     False
8   120542.52       148718.95        311613.29       False    False      True
9   123334.88       108679.17        304981.62        True    False     False
10  101913.08       110594.11        229160.95       False     True     False
11  100671.96        91790.61        249744.55        True    False     False
12   93863.75       127320.38        249839.44       False     True     False
13   91992.39       135495.07        252664.93        True    False     False
14  119943.24       156547.42        256512.92       False     True     False
15  114523.61       122616.84        261776.23       False    False      True
16   78013.11       121597.55        264346.06        True    False     False
17   94657.16       145077.58        282574.31       False    False      True
18   91749.16       114175.79        294919.57       False     True     False
19   86419.70       153514.11             0.00       False    False      True
20   76253.86       113867.30        298664.47        True    False     False
21   78389.47       153773.43        299737.29       False    False      True
22   73994.56       122782.75        303319.26       False     True     False
23   67532.53       105751.03        304768.73       False     True     False
24   77044.01        99281.34        140574.81       False    False      True
25   64664.71       139553.16        137962.62        True    False     False
26   75328.87       144135.98        134050.07       False     True     False
27   72107.60       127864.55        353183.81       False    False      True
28   66051.52       182645.56        118148.20       False     True     False
29   65605.48       153032.06        107138.38       False    False      True
30   61994.48       115641.28         91131.24       False     True     False
31   61136.38       152701.92         88218.23       False    False      True
32   63408.86       129219.61         46085.25        True    False     False
33   55493.95       103057.49        214634.81       False     True     False
34   46426.07       157693.92        210797.67        True    False     False
35   46014.02        85047.44        205517.64       False    False      True
36   28663.76       127056.21        201126.82       False     True     False
37   44069.95        51283.14        197029.42        True    False     False
38   20229.59        65947.93        185265.10       False    False      True
39   38558.51        82982.09        174999.30        True    False     False
40   28754.33       118546.05        172795.67        True    False     False
41   27892.92        84710.77        164470.71       False     True     False
42   23640.93        96189.63        148001.11        True    False     False
43   15505.73       127382.30         35534.17       False    False      True
44   22177.74       154806.14         28334.72        True    False     False
45    1000.23       124153.04          1903.93       False    False      True
46    1315.46       115816.21        297114.46       False     True     False
47       0.00       135426.92             0.00        True    False     False
48     542.05        51743.15             0.00       False    False      True
49       0.00       116983.80         45173.06        True    False     False

In [9]:
y=data["Profit"]
y

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [11]:
x_train.shape

(35, 6)

In [12]:
x_test.shape

(15, 6)

In [13]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train) #training

LinearRegression()

In [14]:
y_pred=model.predict(x_test)   #testing
y_pred

array([126187.39411512,  85788.82259491,  99777.02815161,  45706.12238325,
       127062.20722786,  51891.83884406, 109114.62977498, 100600.61123707,
        97953.99874704, 111730.57706801, 128818.49200667, 174195.35772605,
        93736.28538396, 148381.04097173, 172313.87139382])

In [15]:
df=pd.DataFrame(data={"Predicted value":y_pred,"Actual value":y_test})
df

Predicted value  Actual value
13    126187.394115     134307.35
39     85788.822595      81005.76
30     99777.028152      99937.59
45     45706.122383      64926.08
17    127062.207228     125370.37
48     51891.838844      35673.41
26    109114.629775     105733.54
25    100600.611237     107404.34
32     97953.998747      97427.84
19    111730.577068     122776.86
12    128818.492007     141585.52
4     174195.357726     166187.94
37     93736.285384      89949.14
8     148381.040972     152211.77
3     172313.871394     182901.99

In [16]:
model.intercept_

np.float64(57153.61206156153)

In [17]:
model.coef_

array([ 8.04937292e-01, -9.12577104e-02,  2.80672826e-02,  2.59028652e+02,
        7.17099427e+02, -9.76128080e+02])

In [18]:
#y = bo +b1x1+b2x2+b3x3+ ......b6x6

In [19]:
model.predict([[162305,234589,102567,0,1,0]])

C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([169986.78058413])

In [20]:
#r2 score,rmse,mse or mae

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9397108063367287

In [22]:
model.score(x_test,y_test) #testing data accuracy score

0.9397108063367287

In [23]:
model.score(x_train,y_train)  #training data  model accuracy score

0.9511471170962384

In [24]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_test,y_pred))

np.float64(9210.154995097315)

In [25]:
data.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000