### Random Forest Classifier

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("Diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
x=data.drop("Outcome",axis=1)
y=data["Outcome"]

In [4]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [5]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_test, x_train, y_test, y_train=train_test_split(x,y,test_size=0.20,random_state=42)

In [7]:
from sklearn.tree import DecisionTreeClassifier,plot_tree
classifier=DecisionTreeClassifier()
classifier=classifier.fit(x_train,y_train)

In [8]:
y_predict=classifier.predict(x_test)

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

0.6807817589576547
[[319  82]
 [114  99]]
              precision    recall  f1-score   support

           0       0.74      0.80      0.76       401
           1       0.55      0.46      0.50       213

    accuracy                           0.68       614
   macro avg       0.64      0.63      0.63       614
weighted avg       0.67      0.68      0.67       614



In [10]:
from sklearn.ensemble import RandomForestClassifier   #imprt decision tree 
model=RandomForestClassifier(n_estimators=115,random_state=42)   #n_estimators for howmany trees we want
model=model.fit(x_train,y_train)

In [11]:
y_predict1=model.predict(x_test)

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_predict1))
print(confusion_matrix(y_test,y_predict1))
print(classification_report(y_test,y_predict1))

0.750814332247557
[[345  56]
 [ 97 116]]
              precision    recall  f1-score   support

           0       0.78      0.86      0.82       401
           1       0.67      0.54      0.60       213

    accuracy                           0.75       614
   macro avg       0.73      0.70      0.71       614
weighted avg       0.74      0.75      0.74       614



In [13]:
classifier.predict([[0,23,23,56,12,66,37,789]])

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [14]:
model.predict([[676,23,78,56,688,66,37,789]])

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])