#### Random Forest

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("suv_data.csv")
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
data.drop(["User ID"],axis=1)

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [4]:
data.replace({"Gender":{"Male":0,"Female":1}},inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_12032\2955791427.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({"Gender":{"Male":0,"Female":1}},inplace=True)


In [5]:
x=data.drop("Purchased",axis=1)
y=data["Purchased"]

In [6]:
x

User ID  Gender  Age  EstimatedSalary
0    15624510       0   19            19000
1    15810944       0   35            20000
2    15668575       1   26            43000
3    15603246       1   27            57000
4    15804002       0   19            76000
..        ...     ...  ...              ...
395  15691863       1   46            41000
396  15706071       0   51            23000
397  15654296       1   50            20000
398  15755018       0   36            33000
399  15594041       1   49            36000

[400 rows x 4 columns]

In [7]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_test, x_train, y_test, y_train=train_test_split(x,y,test_size=0.20,random_state=42)

In [9]:
#scalling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
from sklearn.tree import DecisionTreeClassifier,plot_tree
classifier=DecisionTreeClassifier()
classifier=classifier.fit(x_train,y_train)
y_predict=classifier.predict(x_test)

In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

0.84375
[[184  21]
 [ 29  86]]
              precision    recall  f1-score   support

           0       0.86      0.90      0.88       205
           1       0.80      0.75      0.77       115

    accuracy                           0.84       320
   macro avg       0.83      0.82      0.83       320
weighted avg       0.84      0.84      0.84       320



In [12]:
from sklearn.ensemble import RandomForestClassifier   #imprt decision tree 
from sklearn import metrics 
model=RandomForestClassifier(n_estimators=115,random_state=42)   #n_estimators for howmany trees we want
model=model.fit(x_train,y_train)
y_predict1=model.predict(x_test)

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_predict1))
print(confusion_matrix(y_test,y_predict1))
print(classification_report(y_test,y_predict1))

0.8625
[[191  14]
 [ 30  85]]
              precision    recall  f1-score   support

           0       0.86      0.93      0.90       205
           1       0.86      0.74      0.79       115

    accuracy                           0.86       320
   macro avg       0.86      0.84      0.85       320
weighted avg       0.86      0.86      0.86       320



In [14]:
classifier.predict([[56,12,66,37]])

array([1])

In [15]:
model.predict([[688,66,37,789]])

array([1])